### ISSUE TITLE
slim repo size

### ISSUE THREAD

**Issue by toffaletti** [samcoe/gh-repo-explore#6]
The repo (and all its history) is cloned as part of install and it is noticeably slow. Looking at the history, it seems you had previously committed some binary files so they're being retained in the git history. You can do something like https://www.phase2technology.com/blog/removing-large-files-git-bfg to rewrite history and remove the references to the binary files. Be warned rewriting history like this is destructive and should be done with great care. For example, it will probably break your existing tags.

**Comment by toffaletti** [comment]
I see you work on `cli/cli` so perhaps also consider using `--depth 1` here: https://github.com/cli/cli/blob/99cbfd3dd8ea32a27b9545e6ada56a1f4732e90b/pkg/cmd/extension/manager.go#L184
If it makes sense. Thanks for the great tools!

**Comment by samcoe** [comment]
@toffaletti I agree the repo size is a bit large due to initially committing the binary files. The `cli/cli` team has discussed changing the `extension install` command to be a shallow clone and I expect that change will be made in an upcoming release. Knowing that, I am not going to try rewriting the history of this repo to make it smaller, since as you mentioned it is easy for things to get messed up. Now that a pattern of uploading binaries to a release and downloading them on execution has been established, other extension creators can copy it and won't make the same mistake I did. In the future the `cli/cli` team would also like to create some documentation on best practices for writing extensions in compiled languages, since most of the documentation now is for simple `bash` or scripting language extensions.
